<?php

namespace App\Model;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Users extends Model
{
    protected $dateFormat='U';
    protected $casts=[];
    protected $fillable=['no'];

    public function getCreatedAtAttribute($timestamp)
    {
        return Carbon::createFromTimestamp($timestamp)->diffForHumans();
    }
    public function getRouteKeyName()
    {
        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
    }
}
